### ISSUE TITLE
Multimodal support

### ISSUE THREAD

**Issue by wwfcnu** [daily-demos/daily-bots-web-demo#10]
Are there any plans to support multi-modality in the future, such as being able to input pictures, etc.

**Comment by mattieruth** [comment]
Hi! Yes, we plan on expanding the set of bot types we support which includes picture intake.

That said, [this branch](https://github.com/daily-demos/daily-bots-web-demo/tree/lewis/scavenger-hunt-game) includes a modified version of the vision demo that does just this. (This demo is actually a "scavenger hunt" game. If you just want to upload images to an LLM with a more general purpose system prompt, you can look at [this commit](https://github.com/daily-demos/daily-bots-web-demo/commit/9e062811ae03d2f15398be75d2da0cb95de70c0d).)

The game demo uses Anthropic's prompt caching feature, which is currently in beta, but it's quite useful for the image file case, because the LLM prompt can grow quite large when adding image files.

Also, I highly suggest joining our Discord for asking questions like this (this was just asked earlier today :) ): https://discord.com/invite/dailyco
